### ISSUE TITLE
Please add a license and a screen shot

### ISSUE THREAD

**Issue by unixorn** [Vicfs/smelly-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I only add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by Vicfs** [comment]
@unixorn Hey, for sure. I'll do it some time this week and tag you.

**Comment by unixorn** [comment]
Thanks, I'll add it to the list when you tag me or close this issue

**Comment by Vicfs** [comment]
@unixorn Done!
